namespace SqlShop.View.Forms
{
    partial class FrmOrders
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn9 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn10 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn4 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn11 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition3 = new Telerik.WinControls.UI.TableViewDefinition();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn12 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn13 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn14 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn15 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn16 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition4 = new Telerik.WinControls.UI.TableViewDefinition();
            this.RgvOrders = new Telerik.WinControls.UI.RadGridView();
            this.orderBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.RgvOrderDetails = new Telerik.WinControls.UI.RadGridView();
            this.orderDetailsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.label = new Telerik.WinControls.UI.RadLabel();
            this.radLabel1 = new Telerik.WinControls.UI.RadLabel();
            this.btnDelete = new Telerik.WinControls.UI.RadButton();
            this.btnUpdate = new Telerik.WinControls.UI.RadButton();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrders)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrders.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.orderBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrderDetails)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrderDetails.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.orderDetailsBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.label)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.radLabel1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnDelete)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnUpdate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            this.SuspendLayout();
            // 
            // RgvOrders
            // 
            this.RgvOrders.Location = new System.Drawing.Point(12, 54);
            // 
            // 
            // 
            this.RgvOrders.MasterTemplate.AllowAddNewRow = false;
            this.RgvOrders.MasterTemplate.AllowColumnReorder = false;
            this.RgvOrders.MasterTemplate.AllowDragToGroup = false;
            gridViewDecimalColumn9.DataType = typeof(long);
            gridViewDecimalColumn9.FieldName = "OrderId";
            gridViewDecimalColumn9.HeaderText = "آیدی فاکتور";
            gridViewDecimalColumn9.IsAutoGenerated = true;
            gridViewDecimalColumn9.Name = "OrderId";
            gridViewDecimalColumn9.Width = 80;
            gridViewTextBoxColumn3.FieldName = "OrderCode";
            gridViewTextBoxColumn3.HeaderText = "کد فاکتور";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.Name = "OrderCode";
            gridViewTextBoxColumn3.Width = 120;
            gridViewDecimalColumn10.DataType = typeof(long);
            gridViewDecimalColumn10.FieldName = "CustomerId";
            gridViewDecimalColumn10.HeaderText = "آیدی مشتری";
            gridViewDecimalColumn10.IsAutoGenerated = true;
            gridViewDecimalColumn10.Name = "CustomerId";
            gridViewDecimalColumn10.Width = 120;
            gridViewTextBoxColumn4.FieldName = "OrderDate";
            gridViewTextBoxColumn4.HeaderText = "تاریخ";
            gridViewTextBoxColumn4.IsAutoGenerated = true;
            gridViewTextBoxColumn4.Name = "OrderDate";
            gridViewTextBoxColumn4.Width = 130;
            gridViewDecimalColumn11.FieldName = "FinallPrice";
            gridViewDecimalColumn11.HeaderText = "قیمت نهایی";
            gridViewDecimalColumn11.IsAutoGenerated = true;
            gridViewDecimalColumn11.Name = "FinallPrice";
            gridViewDecimalColumn11.Width = 150;
            this.RgvOrders.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn9,
            gridViewTextBoxColumn3,
            gridViewDecimalColumn10,
            gridViewTextBoxColumn4,
            gridViewDecimalColumn11});
            this.RgvOrders.MasterTemplate.DataSource = this.orderBindingSource;
            this.RgvOrders.MasterTemplate.ViewDefinition = tableViewDefinition3;
            this.RgvOrders.Name = "RgvOrders";
            this.RgvOrders.ReadOnly = true;
            this.RgvOrders.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.RgvOrders.Size = new System.Drawing.Size(698, 204);
            this.RgvOrders.TabIndex = 0;
            this.RgvOrders.CurrentRowChanged += new Telerik.WinControls.UI.CurrentRowChangedEventHandler(this.RgvOrders_CurrentRowChanged);
            // 
            // orderBindingSource
            // 
            this.orderBindingSource.DataSource = typeof(SqlShop.DayaLayer.Models.Entity.Order);
            // 
            // RgvOrderDetails
            // 
            this.RgvOrderDetails.Location = new System.Drawing.Point(12, 357);
            // 
            // 
            // 
            this.RgvOrderDetails.MasterTemplate.AllowAddNewRow = false;
            this.RgvOrderDetails.MasterTemplate.AllowColumnReorder = false;
            this.RgvOrderDetails.MasterTemplate.AllowDragToGroup = false;
            gridViewDecimalColumn12.DataType = typeof(long);
            gridViewDecimalColumn12.FieldName = "OrderDetailsId";
            gridViewDecimalColumn12.HeaderText = "آیدی";
            gridViewDecimalColumn12.IsAutoGenerated = true;
            gridViewDecimalColumn12.Name = "OrderDetailsId";
            gridViewDecimalColumn12.Width = 120;
            gridViewDecimalColumn13.DataType = typeof(long);
            gridViewDecimalColumn13.FieldName = "ProductId";
            gridViewDecimalColumn13.HeaderText = "آیدی محصول";
            gridViewDecimalColumn13.IsAutoGenerated = true;
            gridViewDecimalColumn13.Name = "ProductId";
            gridViewDecimalColumn13.Width = 120;
            gridViewDecimalColumn14.FieldName = "UnitPrice";
            gridViewDecimalColumn14.HeaderText = "قیمت واحد";
            gridViewDecimalColumn14.IsAutoGenerated = true;
            gridViewDecimalColumn14.Name = "UnitPrice";
            gridViewDecimalColumn14.Width = 150;
            gridViewDecimalColumn15.FieldName = "Qty";
            gridViewDecimalColumn15.HeaderText = "تعداد";
            gridViewDecimalColumn15.IsAutoGenerated = true;
            gridViewDecimalColumn15.Name = "Qty";
            gridViewDecimalColumn15.Width = 150;
            gridViewDecimalColumn16.FieldName = "Discount";
            gridViewDecimalColumn16.HeaderText = "تخفیف";
            gridViewDecimalColumn16.IsAutoGenerated = true;
            gridViewDecimalColumn16.Name = "Discount";
            gridViewDecimalColumn16.Width = 110;
            this.RgvOrderDetails.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn12,
            gridViewDecimalColumn13,
            gridViewDecimalColumn14,
            gridViewDecimalColumn15,
            gridViewDecimalColumn16});
            this.RgvOrderDetails.MasterTemplate.DataSource = this.orderDetailsBindingSource;
            this.RgvOrderDetails.MasterTemplate.ViewDefinition = tableViewDefinition4;
            this.RgvOrderDetails.Name = "RgvOrderDetails";
            this.RgvOrderDetails.ReadOnly = true;
            this.RgvOrderDetails.RightToLeft = System.Windows.Forms.RightToLeft.Yes;
            this.RgvOrderDetails.Size = new System.Drawing.Size(698, 181);
            this.RgvOrderDetails.TabIndex = 1;
            // 
            // orderDetailsBindingSource
            // 
            this.orderDetailsBindingSource.DataSource = typeof(SqlShop.DayaLayer.Models.Entity.OrderDetails);
            // 
            // label
            // 
            this.label.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.label.Font = new System.Drawing.Font("IRANSans Light", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.label.Location = new System.Drawing.Point(624, 24);
            this.label.Name = "label";
            this.label.Size = new System.Drawing.Size(86, 24);
            this.label.TabIndex = 81;
            this.label.Text = "لیست فاکتورها";
            // 
            // radLabel1
            // 
            this.radLabel1.BackColor = System.Drawing.SystemColors.ActiveCaption;
            this.radLabel1.Font = new System.Drawing.Font("IRANSans Light", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(178)));
            this.radLabel1.Location = new System.Drawing.Point(630, 327);
            this.radLabel1.Name = "radLabel1";
            this.radLabel1.Size = new System.Drawing.Size(80, 24);
            this.radLabel1.TabIndex = 81;
            this.radLabel1.Text = "جزئیات فاکتور";
            // 
            // btnDelete
            // 
            this.btnDelete.Location = new System.Drawing.Point(605, 264);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.Size = new System.Drawing.Size(105, 35);
            this.btnDelete.TabIndex = 83;
            this.btnDelete.Text = "حذف";
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // btnUpdate
            // 
            this.btnUpdate.Location = new System.Drawing.Point(494, 264);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.Size = new System.Drawing.Size(105, 35);
            this.btnUpdate.TabIndex = 83;
            this.btnUpdate.Text = "به روز رسانی";
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // FrmOrders
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(738, 610);
            this.Controls.Add(this.btnUpdate);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.radLabel1);
            this.Controls.Add(this.label);
            this.Controls.Add(this.RgvOrderDetails);
            this.Controls.Add(this.RgvOrders);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmOrders";
            // 
            // 
            // 
            this.RootElement.ApplyShapeToControl = true;
            this.Text = "لیست فاکتور ها";
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrders.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrders)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.orderBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrderDetails.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.RgvOrderDetails)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.orderDetailsBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.label)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.radLabel1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnDelete)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnUpdate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView RgvOrders;
        private Telerik.WinControls.UI.RadGridView RgvOrderDetails;
        private System.Windows.Forms.BindingSource orderBindingSource;
        private System.Windows.Forms.BindingSource orderDetailsBindingSource;
        private Telerik.WinControls.UI.RadLabel label;
        private Telerik.WinControls.UI.RadLabel radLabel1;
        private Telerik.WinControls.UI.RadButton btnDelete;
        private Telerik.WinControls.UI.RadButton btnUpdate;
    }
}
